[advisories]
unmaintained = "all"
ignore = [
    # NOTE: paste which is unmaintained, but
    # is a dependency of tykv-jemalloc-sys
    "RUSTSEC-2024-0436",
    # serde_yaml is unmaintained
    "RUSTSEC-2024-0320",
]

[bans]
deny = [
    # NOTE: `boring`, `ring` or `rustls` crates should be used instead
    { name = "openssl" },
    { name = "openssl-sys" },
]
multiple-versions = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "allow"
allow-git = []

[licenses]
private.ignore = true
unused-allowed-license = "allow"
# Licences should be at least osi or fsf-free
# and not copyleft
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "Unicode-3.0",
    "ISC",
]
confidence-threshold = 0.9
