[package]
name = "foundations-metrics"
description = "Metric types and encoders for the Foundations stack."
version = "0.1.0"
readme = "README.md"
repository = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
categories = ["development-tools", "encoding"]
keywords = ["foundations", "metrics", "prometheus", "openmetrics"]

[package.metadata.release]
pre-release-hook = [
    "git-cliff",
    "-w",
    "..",
    "--include-path",
    "{{crate_name}}/**",
    "--tag-pattern",
    "{{crate_name}}-v[0-9]*",
    "-o",
    "RELEASE_NOTES.md",
    "--tag",
    "{{version}}",
]

[dependencies]
foundations-metrics-registry = { workspace = true }
prometheus-client = { version = "0.25.0", features = [
    "prometheus_protobuf",
    "protobuf-protox",
] }
serde = { workspace = true, features = ["derive"] }
ryu = { workspace = true }
parking_lot = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }

[lints]
workspace = true
